# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            "Nealo's Blog"
tagline:          'virtualise all the cloud stuff in a software defined automation script thing'
description:      'virtualise all the cloud stuffs in a software defined automation script thing, maybe using VMware'
url:              http://www.chrisneale.org
baseurl:          /

author:           Chris Neale
  name:           Nealos Blog
  url:            https://twitter.com/mrcneale

paginate:         5

# Custom vars

github:
  repo:           https://github.com/mrcneale
