# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Nealo's Blog
tagline:          'virtualise all the cloud things in a software defined automation script thing'
description:      'virtualisation, cloud, automation, software-defined and all things of that ilk, with a leaning toward VMware'
url:              http://www.chrisneale.org
baseurl:          /

author:
  name:           'Chris Neale'
  url:            https://twitter.com/mrcneale

paginate:         5

# Custom vars

github:
  repo:           https://github.com/mrcneale
