# Site settings
title: Nealo's Blog
email: chris.neale@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  virtualisation, cloud, automation, software-defined and all things of that ilk, with a leaning toward VMware
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mrcneale
github_username:  mrcneale

# Build settings
markdown: kramdown
